apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-api
  labels:
   app: auth-api
spec:
  replicas: 2
  selector:
    matchLabels:
         app: auth-api
  template:
    metadata:
      labels:
        app: auth-api
    spec:
     containers:
     - name: auth-api
       image: maperez1225/microservice-example-auth:0.0.1
       ports:
        - containerPort: 8000
       env:
       - name: USERS_API_ADDRESS
         value: "http://users-api:8083"
       - name: AUTH_API_PORT
         value: "8000"
       - name: JWT_SECRET
         value: "PRFT"
       - name: ZIPKIN_URL
         value: "http://zipkin:9411"

---
apiVersion: v1
kind: Service
metadata:
 name: auth-api
 labels:
  app: auth-api
spec:
 type: NodePort
 selector:
  app: auth-api
 ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
    name: http