apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-message-processor
  labels:
   app: log-message-processor
spec:
  replicas: 2
  selector:
    matchLabels:
         app: log-message-processor
  template:
    metadata:
      labels:
        app: log-message-processor
    spec:
     containers:
     - name: log-message-processor
       image: maperez1225/microservice-example-logs:0.0.1
       ports:
        - containerPort: 8050
       env:
       - name: REDIS_HOST
         value: "redis"
       - name: REDIS_PORT
         value: "6379"
       - name: REDIS_CHANNEL
         value: "log_channel"
       - name: ZIPKIN_URL
         value: "http://zipkin:9411"

---

apiVersion: v1
kind: Service
metadata:
 name: log-message-processor
 labels:
  app: log-message-processor
spec:
 type: NodePort
 selector:
  app: log-message-processor
 ports:
  - protocol: TCP
    port: 8050
    targetPort: 8050
    name: http