apiVersion: apps/v1
kind: Deployment
metadata:
  name: todos-api
  labels:
   app: todos-api
spec:
  replicas: 1
  selector:
    matchLabels:
         app: todos-api
  template:
    metadata:
      labels:
        app: todos-api
    spec:
     containers:
     - name: todos-api
       image: maperez1225/microservice-example-todos:0.0.1
       ports:
        - containerPort: 8082
       env:
       - name: REDIS_HOST
         value: "redis"
       - name: REDIS_PORT
         value: "6379"
       - name: REDIS_CHANNEL
         value: "log_channel"
       - name: JWT_SECRET
         value: "PRFT"
       - name: TODO_API_PORT
         value: "8082"
       - name: ZIPKIN_URL
         value: "http://zipkin:9411"

---

apiVersion: v1
kind: Service
metadata:
 name: todos-api
 labels:
  app: todos-api
spec:
 type: NodePort
 selector:
  app: todos-api
 ports:
  - protocol: TCP
    port: 8082
    targetPort: 8082
    name: http